[phases.setup]
nixPkgs = ["nodejs_latest"]

[phases.install]
cmds = [
  "npm ci --include=dev --prefix client",
  "npm ci --include=dev --prefix server"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "npm run build --prefix server"
]

[start]
cmd = "cd server && NODE_ENV=production npm start"
